export type ProductCategory = "Essential" | "Relaxed" | "Statement";
export type ProductColor = "Cream" | "Black" | "Rose" | "Sage" | "Brown";

export type Product = {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice?: number;
  category: ProductCategory;
  color: ProductColor;
  colors: ProductColor[];
  rating: number;
  reviewCount: number;
  image: string;
  hoverImage: string;
  gallery: string[];
  badge?: string;
  description: string;
  details: string[];
};

const images = {
  cream: "https://images.pexels.com/photos/17542870/pexels-photo-17542870.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  black: "https://images.pexels.com/photos/9558583/pexels-photo-9558583.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  rose: "https://images.pexels.com/photos/19220726/pexels-photo-19220726.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  sage: "https://images.pexels.com/photos/38625669/pexels-photo-38625669.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  brown: "https://images.pexels.com/photos/20009031/pexels-photo-20009031.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  studio: "https://images.pexels.com/photos/9558765/pexels-photo-9558765.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
  wideCream: "https://images.pexels.com/photos/9558716/pexels-photo-9558716.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1200",
  wideBlack: "https://images.pexels.com/photos/9558902/pexels-photo-9558902.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1200",
  hanger: "https://images.pexels.com/photos/8532611/pexels-photo-8532611.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
};

export const products: Product[] = [
  {
    id: "soft-rib-tee",
    slug: "the-soft-rib-tee",
    name: "The Soft Rib Tee",
    price: 32,
    originalPrice: 42,
    category: "Essential",
    color: "Cream",
    colors: ["Cream", "Black", "Rose", "Sage"],
    rating: 4.9,
    reviewCount: 128,
    image: images.cream,
    hoverImage: images.wideCream,
    gallery: [images.cream, images.wideCream, images.studio],
    badge: "Bestseller",
    description: "A softly structured essential with a subtle rib texture and a beautifully easy fit. Made to be lived in, layered, and loved for years.",
    details: ["95% organic cotton, 5% elastane", "Soft ribbed jersey", "Everyday relaxed fit", "Made in Portugal"],
  },
  {
    id: "essential-tee",
    slug: "the-essential-tee",
    name: "The Essential Tee",
    price: 29,
    category: "Essential",
    color: "Black",
    colors: ["Black", "Cream", "Rose"],
    rating: 4.8,
    reviewCount: 96,
    image: images.black,
    hoverImage: images.wideBlack,
    gallery: [images.black, images.wideBlack, images.hanger],
    description: "The one you reach for on repeat. Clean lines, an easy neckline, and our signature soft cotton jersey.",
    details: ["100% organic cotton", "Lightweight jersey", "Classic everyday fit", "Pre-washed for softness"],
  },
  {
    id: "everyday-tee",
    slug: "the-everyday-tee",
    name: "The Everyday Tee",
    price: 34,
    category: "Essential",
    color: "Rose",
    colors: ["Rose", "Cream", "Black"],
    rating: 4.7,
    reviewCount: 74,
    image: images.rose,
    hoverImage: images.studio,
    gallery: [images.rose, images.studio, images.wideCream],
    badge: "New",
    description: "A considered everyday layer in a quiet rose tone. Easy through the body, refined at the shoulder.",
    details: ["100% organic cotton", "Mid-weight jersey", "Slightly relaxed fit", "Low-impact dyed"],
  },
  {
    id: "relaxed-tee",
    slug: "the-relaxed-tee",
    name: "The Relaxed Tee",
    price: 36,
    category: "Relaxed",
    color: "Cream",
    colors: ["Cream", "Sage", "Black"],
    rating: 4.9,
    reviewCount: 63,
    image: images.wideCream,
    hoverImage: images.cream,
    gallery: [images.wideCream, images.cream, images.brown],
    description: "An effortless, drapey silhouette designed for slow mornings and busy afternoons alike.",
    details: ["100% organic cotton", "Drapey slub jersey", "Relaxed fit", "Dropped shoulder"],
  },
  {
    id: "studio-tee",
    slug: "the-studio-tee",
    name: "The Studio Tee",
    price: 38,
    category: "Relaxed",
    color: "Sage",
    colors: ["Sage", "Cream", "Rose"],
    rating: 4.8,
    reviewCount: 51,
    image: images.sage,
    hoverImage: images.rose,
    gallery: [images.sage, images.rose, images.wideBlack],
    description: "A softly tailored tee in a muted sage that brings a little calm to the everyday.",
    details: ["100% organic cotton", "Compact jersey", "Relaxed fit", "Garment dyed"],
  },
  {
    id: "weekend-tee",
    slug: "the-weekend-tee",
    name: "The Weekend Tee",
    price: 31,
    category: "Relaxed",
    color: "Brown",
    colors: ["Brown", "Cream", "Black"],
    rating: 4.6,
    reviewCount: 45,
    image: images.brown,
    hoverImage: images.wideCream,
    gallery: [images.brown, images.wideCream, images.cream],
    description: "A warm earth tone and a generous fit make this the natural choice for off-duty days.",
    details: ["100% organic cotton", "Soft vintage wash", "Relaxed fit", "Ribbed crew neckline"],
  },
  {
    id: "muse-tee",
    slug: "the-muse-tee",
    name: "The Muse Tee",
    price: 35,
    category: "Statement",
    color: "Rose",
    colors: ["Rose", "Black", "Sage"],
    rating: 4.9,
    reviewCount: 88,
    image: images.studio,
    hoverImage: images.rose,
    gallery: [images.studio, images.rose, images.wideCream],
    badge: "New",
    description: "A softer take on a statement piece, with a graceful neckline and our season's most beautiful rose.",
    details: ["92% organic cotton, 8% elastane", "Fine stretch jersey", "Fitted silhouette", "Designed for layering"],
  },
  {
    id: "classic-tee",
    slug: "the-classic-tee",
    name: "The Classic Tee",
    price: 30,
    category: "Essential",
    color: "Black",
    colors: ["Black", "Cream", "Sage"],
    rating: 4.7,
    reviewCount: 109,
    image: images.wideBlack,
    hoverImage: images.black,
    gallery: [images.wideBlack, images.black, images.hanger],
    description: "A true wardrobe classic, refined down to every seam. The perfect weight for every season.",
    details: ["100% organic cotton", "Smooth jersey", "Classic fit", "Reinforced collar"],
  },
  {
    id: "pure-cotton-tee",
    slug: "the-pure-cotton-tee",
    name: "The Pure Cotton Tee",
    price: 28,
    category: "Essential",
    color: "Cream",
    colors: ["Cream", "Black", "Brown"],
    rating: 4.8,
    reviewCount: 82,
    image: images.hanger,
    hoverImage: images.cream,
    gallery: [images.hanger, images.cream, images.wideCream],
    description: "Pure, uncomplicated, and exceptionally soft. A clean base layer for your everyday uniform.",
    details: ["100% organic cotton", "Breathable jersey", "Easy fit", "Natural corozo buttons"],
  },
  {
    id: "modern-fit-tee",
    slug: "the-modern-fit-tee",
    name: "The Modern Fit Tee",
    price: 37,
    category: "Statement",
    color: "Sage",
    colors: ["Sage", "Rose", "Black"],
    rating: 4.7,
    reviewCount: 39,
    image: images.sage,
    hoverImage: images.wideBlack,
    gallery: [images.sage, images.wideBlack, images.rose],
    description: "A contemporary shape with a sculptural shoulder and considered proportions.",
    details: ["96% organic cotton, 4% elastane", "Dense premium jersey", "Modern fitted shape", "Low-impact dyed"],
  },
  {
    id: "signature-tee",
    slug: "the-signature-tee",
    name: "The Signature Tee",
    price: 42,
    category: "Statement",
    color: "Brown",
    colors: ["Brown", "Cream", "Black"],
    rating: 5,
    reviewCount: 27,
    image: images.brown,
    hoverImage: images.studio,
    gallery: [images.brown, images.studio, images.wideCream],
    badge: "Limited",
    description: "Our most elevated tee, cut with a beautiful drape and finished in a deep, grounding cocoa.",
    details: ["100% extra-long staple cotton", "Silk-touch finish", "Relaxed tailored fit", "Limited seasonal color"],
  },
  {
    id: "minimal-tee",
    slug: "the-minimal-tee",
    name: "The Minimal Tee",
    price: 33,
    category: "Essential",
    color: "Rose",
    colors: ["Rose", "Cream", "Sage"],
    rating: 4.6,
    reviewCount: 58,
    image: images.rose,
    hoverImage: images.cream,
    gallery: [images.rose, images.cream, images.studio],
    description: "The quiet finishing touch. A minimal silhouette with an unexpectedly beautiful hand feel.",
    details: ["100% organic cotton", "Fine jersey", "Straight fit", "Responsibly produced"],
  },
];

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
export const formatPrice = (price: number) => `$${price.toFixed(2)}`;
