import React from 'react';
import { Minus, Plus, Trash2, ArrowRight } from 'lucide-react';
import { useCart } from '../context/CartContext';
import { useLanguage } from '../context/LanguageContext';

interface Props { onNavigate: (page: string) => void; }
export const CartPage: React.FC<Props> = ({ onNavigate }) => {
  const { t } = useLanguage();
  const { items, updateQuantity, removeItem, subtotal, deliveryCharge, total } = useCart();
  return <main className="min-h-screen py-12 sm:py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h1 className="font-serif-display text-4xl font-light mb-8">{t('cart')}</h1>{items.length === 0 ? <div className="text-center py-20 bg-white border border-stone-200 rounded-lg"><p className="font-serif-display text-2xl mb-2">{t('emptyCart')}</p><p className="text-sm text-stone-500 mb-6">{t('emptyCartDesc')}</p><button onClick={() => onNavigate('shop')} className="px-5 py-3 bg-stone-900 text-white rounded text-xs uppercase tracking-widest">{t('continueShopping')}</button></div> : <div className="grid lg:grid-cols-[1fr_340px] gap-8"><div className="space-y-4">{items.map(item => <div key={item.id} className="bg-white border border-stone-200 rounded-lg p-4 flex gap-4"><img src={item.image} alt={item.name} className="w-24 h-28 object-cover rounded bg-stone-100" /><div className="flex-1"><div className="flex justify-between gap-4"><div><h2 className="font-serif-display text-xl">{item.name}</h2><p className="text-xs text-stone-500 mt-1">{item.selectedSize} · {item.selectedColor}</p></div><button onClick={() => removeItem(item.id)} aria-label={t('remove')} className="text-stone-400 hover:text-rose-600"><Trash2 className="w-4 h-4" /></button></div><div className="flex items-center justify-between mt-5"><div className="flex items-center border border-stone-300 rounded"><button onClick={() => updateQuantity(item.id,-1)} className="p-2"><Minus className="w-3 h-3" /></button><span className="w-8 text-center text-xs">{item.quantity}</span><button onClick={() => updateQuantity(item.id,1)} className="p-2"><Plus className="w-3 h-3" /></button></div><p className="font-semibold">৳{(item.price*item.quantity).toLocaleString()}</p></div></div></div>)}</div><aside className="bg-white border border-stone-200 rounded-lg p-6 h-fit"><h2 className="font-serif-display text-2xl mb-5">Order Summary</h2><div className="space-y-3 text-sm"><div className="flex justify-between"><span>{t('subtotal')}</span><span>৳{subtotal.toLocaleString()}</span></div><div className="flex justify-between"><span>{t('delivery')}</span><span>{deliveryCharge ? `৳${deliveryCharge}` : 'Free'}</span></div><div className="pt-3 border-t border-stone-200 flex justify-between font-semibold"><span>{t('total')}</span><span>৳{total.toLocaleString()}</span></div></div><button onClick={() => onNavigate('checkout')} className="w-full mt-6 py-3 bg-stone-900 text-white rounded text-xs uppercase tracking-widest font-semibold flex items-center justify-center gap-2">{t('proceedCheckout')} <ArrowRight className="w-4 h-4" /></button></aside></div>}</div></main>;
};
