import React, { useState } from 'react';
import { useCart } from '../context/CartContext';
import { useLanguage } from '../context/LanguageContext';

interface Props { onNavigate: (page: string) => void; }
export const CheckoutPage: React.FC<Props> = ({ onNavigate }) => {
  const { t } = useLanguage();
  const { items, subtotal, deliveryCharge, total, clearCart } = useCart();
  const [done, setDone] = useState(false);
  const [form, setForm] = useState({ fullName:'', phoneNumber:'', district:'', area:'', fullAddress:'', email:'' });
  const update=(k:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>)=>setForm({...form,[k]:e.target.value});
  if (!items.length && !done) return <main className="min-h-screen py-20 text-center"><h1 className="font-serif-display text-3xl mb-4">{t('emptyCart')}</h1><button onClick={()=>onNavigate('shop')} className="px-5 py-3 bg-stone-900 text-white rounded text-xs uppercase tracking-widest">{t('continueShopping')}</button></main>;
  if (done) return <main className="min-h-screen py-24 text-center px-4"><div className="max-w-lg mx-auto bg-white border border-stone-200 rounded-lg p-10"><h1 className="font-serif-display text-4xl mb-3">Order received</h1><p className="text-sm text-stone-600 mb-7">Thank you, {form.fullName}. We will contact you at {form.phoneNumber} to confirm your Cash on Delivery order.</p><button onClick={()=>onNavigate('home')} className="px-6 py-3 bg-stone-900 text-white rounded text-xs uppercase tracking-widest">Back to Home</button></div></main>;
  return <main className="min-h-screen py-12 sm:py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h1 className="font-serif-display text-4xl font-light mb-8">Checkout</h1><div className="grid lg:grid-cols-[1fr_340px] gap-8"><form onSubmit={e=>{e.preventDefault(); clearCart(); setDone(true);}} className="bg-white border border-stone-200 rounded-lg p-6 space-y-4"><h2 className="font-serif-display text-2xl mb-2">Delivery Information</h2>{[['fullName','Full name'],['phoneNumber','Phone number'],['email','Email address'],['district','District'],['area','Area / Upazila']].map(([key,label])=><input key={key} required={key!=='email'} type={key==='email'?'email':'text'} value={form[key as keyof typeof form]} onChange={update(key as keyof typeof form)} placeholder={label} className="w-full border border-stone-300 rounded px-4 py-3 text-sm outline-none focus:border-stone-800" />)}<textarea required value={form.fullAddress} onChange={update('fullAddress')} placeholder="Full delivery address" rows={4} className="w-full border border-stone-300 rounded px-4 py-3 text-sm outline-none focus:border-stone-800" /><div className="p-4 bg-stone-50 rounded border border-stone-200 text-sm"><strong>Payment:</strong> Cash on Delivery</div><button type="submit" className="w-full py-3 bg-stone-900 text-white rounded text-xs uppercase tracking-widest font-semibold">Place Order · ৳{total.toLocaleString()}</button></form><aside className="bg-white border border-stone-200 rounded-lg p-6 h-fit"><h2 className="font-serif-display text-2xl mb-5">Summary</h2><div className="space-y-3 text-sm"><div className="flex justify-between"><span>{t('subtotal')}</span><span>৳{subtotal.toLocaleString()}</span></div><div className="flex justify-between"><span>{t('delivery')}</span><span>{deliveryCharge ? `৳${deliveryCharge}` : 'Free'}</span></div><div className="border-t pt-3 flex justify-between font-semibold"><span>{t('total')}</span><span>৳{total.toLocaleString()}</span></div></div></aside></div></div></main>;
};
